namespace GTA.Enums
{
    public enum MarkerType
    {
        UpsideDownCone,
        VerticalCylinder,
        ThickChevronUp,
        ThinChevronUp,
        CheckeredFlagRect,
        CheckeredFlagCircle,
        VerticleCircle,
        PlaneModel,
        LostMCDark,
        LostMCLight,
        Number0,
        Number1,
        Number2,
        Number3,
        Number4,
        Number5,
        Number6,
        Number7,
        Number8,
        Number9,
        ChevronUpx1,
        ChevronUpx2,
        ChevronUpx3,
        HorizontalCircleFat,
        ReplayIcon,
        HorizontalCircleSkinny,
        HorizontalCircleSkinnyArrow,
        HorizontalSplitArrowCircle,
        DebugSphere
    }
}