name: 🐛 Bug Report
description: Report a reproducible bug or regression related to ScriptHookVDotNet (SHVDN).
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## Self Check
        - Please note: **ScriptHookVDotNet is NOT ScriptHookV**!
          - If you get the `FATAL: Unknown game version` error after a game update, then this project is not responsible. Instead, you need to wait for [**ScriptHookV**](http://www.dev-c.com/gtav/scripthookv/) to update.
        - Look for similar errors in existing [GitHub Issues](https://github.com/scripthookvdotnet/scripthookvdotnet/issues?q=is%3Aissue) (open or closed) before creating a new issue.
        - Also, you should try using the latest nightly version to make sure your issue has not already been fixed. Nightly builds are available on [a dedicated nightly-release repository](https://github.com/scripthookvdotnet/scripthookvdotnet-nightly/releases).
        - Since the scripting DLLs are supposed to use the ASI that comes from the same version (archive) as those of the DLLs, the versions you're using must match before your bug report can be considered valid. Otherwise, your bug report will be rejected for not meeting one of the requirements.
          - For example, when you use the scripting DLLs from the version `v3.7.0-nightly.52`, use the ASI from it as well. Do not update only the ASI but not the DLLs, and do not update only the DLLs but not the ASI. Update all of them.
          - When you update your SHVDN, make sure you update at least the ASI and scripting DLLs together. You should put or update the pdb files with ones that come from the same archive as the ASI and the DLLs you're using, so we can diagnose your issues more easily.
            - This is not required, but you might want to update the ini file unless you're sure the available options have not changed between the version you were using and the new version you want to use.
        - If you are not familiar with how to program and you are encountering some issues related to some SHVDN scripts, such as compatibility issues due to game versions, please try to seek help from the authors and ask them to find out the causes.
          - If the issue is due to the use of nightly methods or properties that are not included in any stable releases, it will be closed as not planned/valid, as the script did not follow one of the API compatibility contracts. Contact the author(s) of the script and ask them to build the script against a stable version in that case.
  - type: dropdown
    id: modules-with-problem
    validations:
      required: true
    attributes:
      label: 📦 What modules are you seeing the problem on?
      multiple: true
      options:
        - ScriptHookVDotNet.asi (core/runtime)
        - ScriptHookVDotNet3.dll (v3 SDK/API)
        - ScriptHookVDotNet2.dll (v2 SDK/API)
  - type: input
    id: shvdn-version
    validations:
      required: true
    attributes:
      label: 🛠️ SHVDN Version
      description: |
        For nightly versions, write a nightly version such as `v3.7.0-nightly.52` or write a unique commit hash (like 201d573) in the main repository. Don't use a short commit hash of fewer than 7 characters to avoid easy hash collisions.
        Each nightly release in the nightly auto-release repository includes the short and full commit hash of the corresponding commit in the main repository.
        Reporting bugs with a short commit hash is acceptable in most cases. If the main branch contains multiple hashes starting with a short commit hash, you could report with the full hash in this case.
        Do not write a commit hash in the nightly auto-release repository, as commits in it are not tied to specific SHVDN commits in the main repository!
        Do not use the console to check when you are using a nightly version, because it does not report a nightly number.

        For stable release versions, open the console to check. However, you should try the latest nightly version to make sure your issue has not already been fixed.
      placeholder: "0d5b09b"
  - type: input
    id: game-version
    validations:
      required: true
    attributes:
      label: 🎮 Game Version
      description: | 
        See ScriptHookV.log to check. You should see a string like "VER_1_0_2845_0", and convert it to like "v1.0.2845.0" to fill in.
        Pirated versions are not acceptable, and the created issue will be closed as not planned (unless it's reproducible with some legitimate versions).
      placeholder: "v1.0.2845.0"
  - type: textarea
    id: bug-desc
    validations:
      required: true
    attributes:
      label: 🐛 Bug Description
      description: |
       Please provide a clear and concise description of what the bug is. Include appropriate logs or screenshots if needed.
       Please test using the latest nightly version of SHVDN to make sure your issue has not already been fixed.
  - type: textarea
    id: steps-to-repro
    validations:
      required: true
    attributes:
      label: 🔄 Steps To Reproduce
      description: |
        Steps to reproduce the problem.
        Your bug will get fixed much faster if we can run your code, and it doesn't have dependencies other than the SHVDN SDK.
        Issues without reproduction steps or code examples may be immediately closed as not actionable.
      placeholder: |
        For example:
        1. Try to get the oil level of a vehicle via Vehicle.OilLevel
        2. Always returns zero

        Another example:
        1. Enumerate a WeaponComponentCollection instance via foreach
        2. The SHVDN runtime crashes, and ScriptHookV shows the string "CORE: An exception occurred while executing"
  - type: input
    id: link-to-code-example
    validations:
      required: false
    attributes:
      label: 📄 Link To Code Example
      description: |
        Please provide a link to a minimal code example if the bug is related to an API layer, and the Steps To Reproduce aren't enough to describe the bug.
  - type: textarea
    id: current-behavior
    validations:
      required: true
    attributes:
      label: ⚠️ Current Behavior
      description: A brief description of what is happening.
  - type: textarea
    id: expected-behavior
    validations:
      required: true
    attributes:
      label: 🎯 Expected Behavior
      description: A brief description of what should happen.
