//
// Copyright (C) 2015 crosire & kagikn & contributors
// License: https://github.com/scripthookvdotnet/scripthookvdotnet#license
//

namespace GTA
{
	public enum CheckpointIcon
	{
		CylinderSingleArrow,
		CylinderDoubleArrow,
		CylinderTripleArrow,
		CylinderCycleArrow,
		CylinderCheckerboard,
		CylinderWrench,
		CylinderSingleArrow2,
		CylinderDoubleArrow2,
		CylinderTripleArrow2,
		CylinderCycleArrow2,
		CylinderCheckerboard2,
		CylinderWrench2,
		RingSingleArrow,
		RingDoubleArrow,
		RingTripleArrow,
		RingCycleArrow,
		RingCheckerboard,
		SingleArrow,
		DoubleArrow,
		TripleArrow,
		CycleArrow,
		Checkerboard,
		CylinderSingleArrow3,
		CylinderDoubleArrow3,
		CylinderTripleArrow3,
		CylinderCycleArrow3,
		CylinderCheckerboard3,
		CylinderSingleArrow4,
		CylinderDoubleArrow4,
		CylinderTripleArrow4,
		CylinderCycleArrow4,
		CylinderCheckerboard4,
		CylinderSingleArrow5,
		CylinderDoubleArrow5,
		CylinderTripleArrow5,
		CylinderCycleArrow5,
		CylinderCheckerboard5,
		RingPlaneUp,
		RingPlaneLeft,
		RingPlaneRight,
		RingPlaneDown,
		Empty,
		Ring,
		Empty2,
		//CylinderCustomShape,
		//CylinderCustomShape2,
		//CylinderCustomShape3,
		Cyclinder = 47,
		Cyclinder2,
		Cyclinder3,
	}
}
